name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev-portfolio-v1 repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Clone lusanco.github.io repository
        uses: actions/checkout@v3
        with:
          repository: Lusanco/lusanco.github.io
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }} # Use your PAT here
          path: lusanco.github.io

      - name: Create docs folder and copy build output
        run: |
          rm -rf lusanco.github.io/docs/*
          mkdir -p lusanco.github.io/docs
          cp -r ./docs/* lusanco.github.io/docs

      - name: Commit and push changes
        run: |
          cd lusanco.github.io
          git config --global user.email "lasc1026@gmail.com"
          git config --global user.name "Lusanco"
          git add .
          git commit -m "Deploy new build"
          git push https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Lusanco/lusanco.github.io.git
